# Generated by Django 5.1.3 on 2024-12-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger_profile_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='BloggerProfileImage/')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.blogger_register')),
            ],
        ),
        migrations.CreateModel(
            name='User_profile_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='UserProfileImage/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_register')),
            ],
        ),
    ]
